name: graphql_to_dart
description: A simple command-line application that converts graphql files to dart constants.

environment:
  sdk: '>=2.10.0 <3.0.0'
 

dependencies:
  args: ^1.6.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
