name: graphql_to_dart
description: A simple command-line application that converts graphql files to dart constants.

environment:
  sdk: '>=2.12.0 <3.0.0'
 

dependencies:
  args: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
